/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app_hanoistyle;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.extras.components.FlatCheckBox;
import com.formdev.flatlaf.intellijthemes.FlatArcDarkIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatArcIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatDarkFlatIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatMonocaiIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatGitHubDarkIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatSolarizedDarkIJTheme;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author ADMIN
 */
public class Login_app extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login_app() {
        initComponents();
    }
    boolean chuyenGiaoDien = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPassword = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPassword.setBackground(new java.awt.Color(107, 34, 47));
        txtPassword.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword.setToolTipText("");
        txtPassword.setSelectionColor(new java.awt.Color(114, 0, 59));
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 220, -1));

        jButton1.setBackground(new java.awt.Color(189, 121, 153));
        jButton1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(247, 247, 247));
        jButton1.setText("Log in");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trenpho_small_1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordFocusLost


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        String password = JOptionPane.showInputDialog(this, "Nhập password:");
//        String password = txtPassword.getText();
//        if (password.equals("admin01")) {
//
//            dispose(); // Đóng cửa sổ hiện tại
//
//            // Mở JFrame mới
//            chuyenGiaoDien = true;
//            app_hanoistyle app = new app_hanoistyle();
//            app.setVisible(true);
//            app.setLocation(null);
//
//            //đóng JFrame
////                    Login_app login = new Login_app();
////                    login.setVisible(false);
//        } else {
//            // Xử lý khi đăng nhập không thành công
//            JOptionPane.showMessageDialog(this, "Đăng nhập không thành công!");
//        }

        String password = txtPassword.getText();
        
        if (password.equals("admin01")) {
//            dispose(); // Đóng cửa sổ hiện tại

            // Mở JFrame mới
            app_hanoistyle app = new app_hanoistyle();
            app.setVisible(true);
            app.setLocationRelativeTo(null);


//            try {
//                UIManager.setLookAndFeel(new FlatLightLaf());
//                SwingUtilities.updateComponentTreeUI(app); //để cập nhật giao diện người dùng của một thành phần (component) và tất cả các thành phần con của nó dựa trên Look and Feel hiện tại
//                app.invalidate(); 
//                app.validate();
//                app.repaint();
//                //để đảm bảo rằng UI của thành phần app sẽ được vẽ lại để hiển thị những thay đổi đã áp dụng. invalidate() sẽ đánh dấu rằng cần phải vẽ lại, validate() sẽ đảm bảo rằng layout của thành phần đã được cập nhật, và repaint() sẽ thực hiện việc vẽ lại UI.
//            } catch (UnsupportedLookAndFeelException e) {
//                e.printStackTrace();
//            }
        } else {
            JOptionPane.showMessageDialog(this, "Đăng nhập không thành công!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Login_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Login_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Login_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Login_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
//        try {
//            UIManager.setLookAndFeel(new FlatSolarizedDarkIJTheme());
//        } catch (Exception ex) {
//            System.err.println("Failed to initialize LaF");
//        }
//
//        Login_app login = new Login_app();
//        app_hanoistyle app =  new app_hanoistyle();
//        login.setLocationRelativeTo(null);
//        // Show the main application frame
//
//
//        // Check if the main application frame is visible
//        if (Boolean.TRUE) {
//            // If visible, change the Look and Feel to FlatLightLaf
//            try {
//                UIManager.setLookAndFeel(new FlatLightLaf());
////                SwingUtilities.updateComponentTreeUI(app);
////                app.invalidate();
////                app.validate();
////                app.repaint();
//            } catch (UnsupportedLookAndFeelException e) {
//                e.printStackTrace();
//            }
//        }
        try {
            UIManager.setLookAndFeel(new FlatSolarizedDarkIJTheme());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }

//        Login_app login = new Login_app();
//
//        // Check if the main application frame is visible
//        if (login.chuyenGiaoDien == true) {
//            // If visible, change the Look and Feel to FlatLightLaf
//            try {
//                UIManager.setLookAndFeel(new FlatLightLaf());
//                SwingUtilities.updateComponentTreeUI(login);
//                login.invalidate();
//                login.validate();
//                login.repaint();
//            } catch (UnsupportedLookAndFeelException e) {
//                e.printStackTrace();
//            }
//        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_app().setVisible(true);
//                Login_app login =  new Login_app();
//                login.setLocation(null);
//                app_hanoistyle app = new app_hanoistyle();
//                app.setLocation(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
